### What is a Tensor?

#### 1. Creating Tensors

- A tensor is the basic data structure in PyTorch.
- AI models only understand tensors, not raw Python objects
- Tensors generalize scalars, vectors, and matrices
<br>
<br>
- 0D tensor → scalar
- 1D tensor → vector
- 2D tensor → matrix
- 3D+ tensor → images, batches, sequences

In [7]:
import torch

a = torch.tensor([1, 2, 3])

b = torch.zeros(3)
c = torch.ones(3)

d = torch.rand(3)

display(a, b, c, d)

tensor([1, 2, 3])

tensor([0., 0., 0.])

tensor([1., 1., 1.])

tensor([0.6236, 0.4781, 0.7396])

- torch.tensor() infers datatype automatically
- torch.rand() gives values in range $[0, 1)$

#### 2. Tensor Data Types (dtype)

In [11]:
x = torch.tensor([1, 2, 3])

y = torch.tensor([1, 2, 3], dtype=torch.float32)

display(x.dtype, y.dtype)

torch.int64

torch.float32

Common dtypes:
- torch.int64 → integers (default for whole numbers)
- torch.float32 → most used in deep learning

Why floats?
Because gradients are real numbers, not integers.

#### 3. Tensor Shape & Dimensions

In [17]:
t = torch.tensor([
            [1, 2, 3],
            [4, 5, 6]
])

display(t.shape)

torch.Size([2, 3])

Meaning:
- 2 rows
- 3 columns

Rank (dimensions):
- 1D → vector
- 2D → matrix
- 3D+ → tensors

#### 4. Reshaping Tensors
(same as numpy)

In [23]:
x = torch.arange(6)
display(x)

tensor([0, 1, 2, 3, 4, 5])

In [27]:
x_reshaped = x.reshape(2, 3)
display(x_reshaped)

tensor([[0, 1, 2],
        [3, 4, 5]])

- Total number of elements must match
- -1 lets PyTorch infer size automatically

In [28]:
x.reshape(-1, 2)

tensor([[0, 1],
        [2, 3],
        [4, 5]])

#### 5. Tensor Operations
(same as numpy)

In [32]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([10, 20, 30])

display(a+b)
display(a*b)

tensor([11, 22, 33])

tensor([10, 40, 90])

##### Matrix multiplication:

In [34]:
m1 = torch.rand(2, 3)
m2 = torch.rand(3, 2)

display(m1, m2)

torch.matmul(m1, m2)

tensor([[0.4830, 0.2497, 0.7466],
        [0.4328, 0.4921, 0.3862]])

tensor([[0.7988, 0.1981],
        [0.7198, 0.4104],
        [0.0351, 0.5767]])

tensor([[0.5918, 0.6287],
        [0.7135, 0.5104]])

#### 6. Tensor vs NumPy

In [36]:
import numpy as np

np_arr = np.array([1, 2, 3])

torch_arr = torch.from_numpy(np_arr)

display(np_arr)
display(torch_arr)

array([1, 2, 3])

tensor([1, 2, 3])

Key points:
- Memory is shared
- Changing one affects the other

In [37]:
np_arr[0] = 99

display(torch_arr)

tensor([99,  2,  3])