### What a neural network really is

A neural network is just a function.

Input → some math → output

Example idea:
- input: number
- output: another number

Inside the network:
- multiply
- add
- apply a simple rule

### The most basic building block — nn.Linear

In [27]:
import torch
import torch.nn as nn

In [28]:
layer = nn.Linear(in_features=1, out_features=1)

What this means:

- input size = 1
- output size = 1
- internally PyTorch creates:
- a weight
- a bias

Mathematically:

$y = wx + b$

- $x$ → input data (the number you feed into the model)
- $w$ → weight (how important the input is)
- $b$ → bias (shifts the output up or down)

### Passing data through the layer (forward pass)

In [29]:
x = torch.tensor([3.0])
y = layer(x)

print(y)

tensor([-1.4523], grad_fn=<ViewBackward0>)


What happened:

- input went in
- PyTorch applied $wx + b$
- output came out

At this stage:
- weights are random
- output is meaningless
- this is normal

### What is nn.Module and why we need it

When networks grow bigger, we need:
- structure
- reusability
- automatic parameter tracking

That’s why we use nn.Module.

### Define your own neural network

In [30]:
class SimpleNet(nn.Module):     #inherit nn.Module
    def __init__(self):
        super().__init__()      #inherit constructor of parent class (nn.Module)
        self.linear = nn.Linear(1, 1)
        
    def forward(self, x):
        return self.linear(x)

- SimpleNet → your model
- __init__ → define layers
- self.linear → one linear layer
- forward → how data flows

This is the model.

### Create and use the model

In [31]:
model = SimpleNet()

x = torch.tensor([3.0])
y = model(x)

print(y)

tensor([1.0283], grad_fn=<ViewBackward0>)


- calling model(x) automatically calls forward
- this is a PyTorch feature, not Python

### Where are the weights?

In [32]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[0.6219]], requires_grad=True)
Parameter containing:
tensor([-0.8373], requires_grad=True)


You’ll see:
- weight
- bias

Both have:
- requires_grad=True
- meaning: they can learn

### Add an activation function (optional but important)

Without activation:
- model is just linear

Add ReLU (Rectified Linear Unit):

In [36]:
class SimpleNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)
        self.relu = nn.ReLU()
        
    def forward(self, x):
        x = self.linear(x)
        y = self.relu(x)
        
        return x, y
    
model = SimpleNet()
x = torch.tensor([3.0])
y = model(x)
print(y)

(tensor([1.6117], grad_fn=<ViewBackward0>), tensor([1.6117], grad_fn=<ReluBackward0>))


Now:
- negative values → 0
- model becomes non-linear

#### Key mental model

- nn.Linear → does math
- forward() → defines flow
- model parameters → learnable numbers
- autograd → updates them

In [ ]:
x = torch.tensor([3.0])

layer = nn.Linear(in_features=1, out_features=2)
print(layer(x))

tensor([0.6621, 3.3272], grad_fn=<ViewBackward0>)
